#!/usr/bin/env bash
# Displays informtation about subdomains.
# Usage: ./0-world_wide_web.sh <domain> <subdomain>
# Example: ./0-world_wide_web.sh hbtn.io www

# Configure my domain zone:
# www --> 78716-lb-01 54.160.93.43
# lb-01 --> 78716-web-01 54.160.93.43
# web-01 --> 78716-web-01 100.26.10.20
# web-02 --> 78716-web-02 100.26.56.219

# -- To be evaluated --
# domain_information () {
#     line=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
#     echo "$2 $line" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
# }

# uncomment for debugging purposes.
# set -x

# for the checker to work please remove the colors.

# colors
# blue='\e[1;34m'
# brown='\e[0;33m'
# reset='\033[0m'

# variables & parameters
subdomains=( "www" "lb-01" "web-01" "web-02" )
domain="$1"
sub="$2"

dig_cmd () {
	# func variables
	sub="$2"
	INFO="$(dig "$sub.$domain" | grep -A1 'ANSWER SECTION:' | awk 'NR==2')"
	IP=$(echo "$INFO" | awk '{print $5}')
	RECORD=$(echo "$INFO" | awk '{print $4}')

	# echo -e "${brown}The subdomain ${blue}$sub${brown} is a ${blue}$RECORD${brown} record and points to ${blue}$IP${reset}"
	echo -e "The subdomain $sub is a $RECORD record and points to $IP"
}

if [ $# -lt 1 ]; then
    echo "Usage: 0-world_wide_web.sh <domain> <subdomain>"
elif [ $# -eq 1 ]; then
	for subs in "${subdomains[@]}"; do
		dig_cmd "$domain" "$subs"
	done
elif [ $# -eq 2 ]; then
	dig_cmd "$domain" "$sub"
fi
