#!/usr/bin/env bash
# A script that:
# 	Parses Apache log files in list format
# 	Groups visitors by IP and HTTP status code
# 	Displays the number of occurrences, IP, and HTTP status code of each login sorted order

FILE_NAME="apache-access.log"
if test -f $FILE_NAME; then
  awk '{print $1,$9}' $FILE_NAME | sort | uniq -c | sort -gr
fi
