#!/usr/bin/env bash
# A script that loops 20 times using the "while" loop and:
# 	displays "4" and then "bad luck from China" for the 4th loop iteration
# 	displays "9" and then "bad luck from Japan" for the 9th loop iteration
# 	displays "17" and then "bad luck from Italy" for the 17th loop iteration

COUNTER=1
while [ $COUNTER -lt 21 ]
do
	echo $COUNTER
        case $COUNTER in
	4)
		echo "bad luck from China"
		;;
	9)
		echo "bad luck from Japan"
		;;
	17)
		echo "bad luck from Italy"
		;;
	esac
	COUNTER=$((COUNTER+1))
done
