#!/usr/bin/env bash
# A script that displays:
#	The content of the current directory
# 	In a list format
# 	Where only the part of the name after the first dash is displayed (refer to the example)

for file in *; do
	file=$(echo  "$file" | cut -f 2 -d '-')
	echo "$file"
done
